name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_RELEASE_USER }}
          password: ${{ secrets.DOCKER_RELEASE_PASS }}

      - name: Build Docker image
        run: docker build -t nirav96/k8s_dashboard:latest modules/web

      - name: Push Docker image
        run: docker push nirav96/k8s_dashboard:latest
